# Generated by Django 4.1.7 on 2023-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_bank_transcations_voucher_contra_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='con_particular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
