# Generated by Django 4.1.7 on 2023-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_bank_transcations_con_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='con_voucher',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
